
-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `requisitos`
--

CREATE TABLE `requisitos` (
  `id` int(20) NOT NULL,
  `ejeybordesinclasificar` tinyint(1) DEFAULT NULL,
  `ejeybordeclasificados` tinyint(1) DEFAULT NULL,
  `banquinapavimentada` tinyint(1) DEFAULT NULL,
  `bordedecamino` tinyint(1) DEFAULT NULL,
  `caminossecundarios` tinyint(1) DEFAULT NULL,
  `carrildesaceleracion` tinyint(1) DEFAULT NULL,
  `accesos` tinyint(1) DEFAULT NULL,
  `huellasentranqueras` tinyint(1) DEFAULT NULL,
  `darsenas` tinyint(1) DEFAULT NULL,
  `cordones` tinyint(1) DEFAULT NULL,
  `manzanas` tinyint(1) DEFAULT NULL,
  `limitedecalzada` tinyint(1) DEFAULT NULL,
  `cotasenbordesyeje` tinyint(1) DEFAULT NULL,
  `lineaselectricas` tinyint(1) DEFAULT NULL,
  `postesdelineaselectricas` tinyint(1) DEFAULT NULL,
  `transformadores` tinyint(1) DEFAULT NULL,
  `postesdeiluminacion` tinyint(1) DEFAULT NULL,
  `galibos` tinyint(1) DEFAULT NULL,
  `alambrados` tinyint(1) DEFAULT NULL,
  `tranqueras` tinyint(1) DEFAULT NULL,
  `guardaganados` tinyint(1) DEFAULT NULL,
  `postedetranquera` tinyint(1) DEFAULT NULL,
  `cercodemadera` tinyint(1) DEFAULT NULL,
  `cercometalico` tinyint(1) DEFAULT NULL,
  `edificaciones` tinyint(1) DEFAULT NULL,
  `perfilestransversales` tinyint(1) DEFAULT NULL,
  `garitas` tinyint(1) DEFAULT NULL,
  `alcantarillassindatos` tinyint(1) DEFAULT NULL,
  `alcantarillascondatos` tinyint(1) DEFAULT NULL,
  `alcantarillastransversales` tinyint(1) DEFAULT NULL,
  `alcantarillaslaterales` tinyint(1) DEFAULT NULL,
  `barandasmetalicas` tinyint(1) DEFAULT NULL,
  `carteles` tinyint(1) DEFAULT NULL,
  `pretiles` tinyint(1) DEFAULT NULL,
  `mojonkilometrico` tinyint(1) DEFAULT NULL,
  `señalizacionhorizontal` tinyint(1) DEFAULT NULL,
  `espaciosverdes` tinyint(1) DEFAULT NULL,
  `destinos` tinyint(1) DEFAULT NULL,
  `puentes` tinyint(1) DEFAULT NULL,
  `luminarias` tinyint(1) DEFAULT NULL,
  `viasferrocarril` tinyint(1) DEFAULT NULL,
  `estacionesferroviarias` tinyint(1) DEFAULT NULL,
  `semaforos` tinyint(1) DEFAULT NULL,
  `telefoniadeemergencia` tinyint(1) DEFAULT NULL,
  `lomosdeburro` tinyint(1) DEFAULT NULL,
  `gasoducto` tinyint(1) DEFAULT NULL,
  `umbrales` tinyint(1) DEFAULT NULL,
  `puntosfijos` tinyint(1) DEFAULT NULL,
  `arboles` tinyint(1) DEFAULT NULL,
  `aguarios` tinyint(1) DEFAULT NULL,
  `basculas` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
